### ISSUE TITLE
when child is a listView,scrollbar behaves improperly.

### ISSUE THREAD

**Issue by leavky** [woltapp/wolt_modal_sheet#46]
Thank you very much for releasing this package, it's been very helpful. I have encountered an issue while using it, specifically with the scrolling behavior. When I set the child to be a ListView or ReorderableListView, the scrollbar behaves improperly. Additionally, when the child is a ReorderableListView, the drag-and-drop sorting becomes very laggy.

**Comment by ulusoyca** [comment]
Hi, thanks for the feedback. Can you please provide sample code to reproduce and also the screen recording?

**Comment by leavky** [comment]
code in example, just replace child as  ListView.builder.
```
    WoltModalSheetPage page1(BuildContext modalSheetContext, TextTheme textTheme) {
      return WoltModalSheetPage.withSingleChild(
        stickyActionBar: Padding(
          padding: const EdgeInsets.all(_pagePadding),
          child: Column(
            children: [
              ElevatedButton(
                onPressed: () => Navigator.of(modalSheetContext).pop(),
                child: const SizedBox(
                  height: _buttonHeight,
                  width: double.infinity,
                  child: Center(child: Text('Cancel')),
                ),
              ),
              const SizedBox(height: 8),
              ElevatedButton(
                onPressed: () => pageIndexNotifier.value = pageIndexNotifier.value + 1,
                child: const SizedBox(
                  height: _buttonHeight,
                  width: double.infinity,
                  child: Center(child: Text('Next page')),
                ),
              ),
            ],
          ),
        ),
        topBarTitle: Text('Pagination', style: textTheme.titleSmall),
        isTopBarLayerAlwaysVisible: true,
        leadingNavBarWidget: IconButton(
          padding: const EdgeInsets.all(_pagePadding),
          icon: const Icon(Icons.arrow_back_rounded),
          onPressed: () => pageIndexNotifier.value = pageIndexNotifier.value - 1,
        ),
        trailingNavBarWidget: IconButton(
          padding: const EdgeInsets.all(_pagePadding),
          icon: const Icon(Icons.close),
          onPressed: Navigator.of(modalSheetContext).pop,
        ),
        child: Padding(
          padding: const EdgeInsets.fromLTRB(
            _pagePadding,
            _pagePadding,
            _pagePadding,
            _bottomPaddingForButton,
          ),
          child: SizedBox(
            height: 400,
            child: ListView.builder(
                itemCount: 100,
                itemBuilder: (context, index) {
                  return Text(index.toString());
                }),
          ),
        ),
      );
    }
```
![image](https://github.com/woltapp/wolt_modal_sheet/assets/46547390/1287d500-0da6-4016-b653-5e475256fd60)

**Comment by leavky** [comment]
also in coffee_maker, in windows, the scroll hehavior so strangeness, when drag scrollerbar print `Exception caught by gestures library`
![image](https://github.com/woltapp/wolt_modal_sheet/assets/46547390/1b1af1ce-a12f-48e0-9576-3c8c28e82a9a)

**Comment by ulusoyca** [comment]
@leavky First of all, if the main content is scrollable, you should use `sliverList` of the page view instead of `withSingleChild` since `sliverList` builds the main content items lazily.

Thanks for reporting the issue regarding the extra scroll bar shown in web and desktop apps. [This PR] (https://github.com/woltapp/wolt_modal_sheet/pull/58)fixes this issue.

@rydmike I can reproduce the exception thrown when scrollbar is dragged in MAC app. It is due to the `DragScrollBehavior` I use here that I took from FlexColorScheme. Are you familiar with it?

```dart
When the exception was thrown, this was the stack: 
#2      RenderFractionalTranslation.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2962:12)
#3      RenderFractionalTranslation.hitTest (package:flutter/src/rendering/proxy_box.dart:2949:12)
#4      RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#5      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#6      RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:88:24)
#7      BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#8      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:83:21)
#9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#10     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#12     RenderClipRect.hitTest (package:flutter/src/rendering/proxy_box.dart:1540:18)
#13     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2858:25)
#14     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#15     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2853:33)
#16     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:630:12)
#17     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#18     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2858:25)
#19     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#20     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2853:33)
#21     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:630:12)
#22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#23     _RenderLayoutBuilder.hitTestChildren (package:flutter/src/widgets/layout_builder.dart:332:19)
#24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#25     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#26     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#27     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#28     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:544:18)
#29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#30     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#32     RenderPhysicalShape.hitTest (package:flutter/src/rendering/proxy_box.dart:2132:18)
#33     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#34     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#35     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#36     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#37     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2858:25)
#38     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#39     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2853:33)
#40     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:413:12)
#41     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#42     RenderShiftedBox.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/shifted_box.dart:88:24)
#43     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#44     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:83:21)
#45     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#46     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2858:25)
#47     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#48     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2853:33)
#49     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:630:12)
#50     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#51     RenderBoxContainerDefaultsMixin.defaultHitTestChildren.<anonymous closure> (package:flutter/src/rendering/box.dart:2858:25)
#52     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#53     RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2853:33)
#54     RenderCustomMultiChildLayoutBox.hitTestChildren (package:flutter/src/rendering/custom_layout.dart:413:12)
#55     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#56     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#57     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#58     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#59     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#60     RenderPhysicalModel.hitTest (package:flutter/src/rendering/proxy_box.dart:2008:18)
#61     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#62     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#63     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#64     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#65     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3634:31)
#66     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#67     RenderTransform.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:2555:22)
#68     BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:837:31)
#69     BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:767:12)
#70     RenderTransform.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:2551:19)
#71     RenderTransform.hitTest (package:flutter/src/rendering/proxy_box.dart:2545:12)
#72     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#73     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#74     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#75     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#76     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#77     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#78     RenderOffstage.hitTest (package:flutter/src/rendering/proxy_box.dart:3757:31)
#79     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#80     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#81     _RenderTheaterMixin.hitTestChildren.childHitTest (package:flutter/src/widgets/overlay.dart:850:81)
#82     BoxHitTestResult.addWithPaintOffset (package:flutter/src/rendering/box.dart:801:31)
#83     _RenderTheaterMixin.hitTestChildren (package:flutter/src/widgets/overlay.dart:851:22)
#84     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#85     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#86     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#87     RenderAbsorbPointer.hitTest (package:flutter/src/rendering/proxy_box.dart:3867:17)
#88     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#89     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:190:19)
#90     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#91     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#92     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#93     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:544:18)
#94     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#95     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#96     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#97     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#98     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#99     RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#100    RenderTapRegionSurface.hitTest (package:flutter/src/widgets/tap_region.dart:213:28)
#101    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#102    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#103    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#104    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#105    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#106    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#107    RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:137:19)
#108    RenderBox.hitTest (package:flutter/src/rendering/box.dart:2479:11)
#109    RenderView.hitTest (package:flutter/src/rendering/view.dart:189:14)
#110    RenderView.hitTestMouseTrackers (package:flutter/src/rendering/view.dart:203:5)
#111    RendererBinding.dispatchEvent.<anonymous closure> (package:flutter/src/rendering/binding.dart:329:79)
#112    MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:300:92)
#113    RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:323:20)
#114    GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:400:7)
#115    GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:363:5)
#116    GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:320:7)
#117    GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:293:9)
#118    _invoke1 (dart:ui/hooks.dart:158:13)
#119    PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:382:7)
#120    _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

```

**Comment by rydmike** [comment]
Without looking into the details of this particular case, one issue I have seen on desktop, that seems very related to this, is that on desktop, scrollbars will appear by default where they are not seen on phones/tablets, this may cause issues with multiple scrollbars and where the default scroll controller belongs to both, which will cause a similar assert error. At least that is what I recall from seeing this issue before in the Themes Playground app.

What worked for me, in cases where both scrolling regions were needed, was to totally disable the scrollbar on the widget that should not have one (in the issue image you have two scrollbars for different scrolling regions, you probably only want one) and make sure you have only one scroll controller per scrolling surface, meaning you may have to create a scroll controller manually for them, to make them unique.

You can also try setting the 'primary: true' property on the list view that should be the main one if there are multiple ones, but I honestly don't remember if that helped at all, probably not.

It has been a while since I looked at my similar case, so I am just throwing what I recall from it on the wall. Sorry, I am on a phone now, so I can't look at the details. Without trying the reproduction sample and seeing the assert, and attempting a fix for it, I can't be 100% sure it is the same situation, but it sounds and looks very similar.

Sometimes you can also get rid of the widget causing the 2nd scrolling area and having them in the same scrolling area, depends on the use case of course.

**Comment by ulusoyca** [comment]
I found out that it is not the scroll bars causing this exceptions but the drag behavior on desktop @rydmike since I did this:
```dart
final scrollView = CustomScrollView(
      scrollBehavior: (const DragScrollBehavior()).copyWith(scrollbars: false),
```

**Comment by TahaTesser** [comment]
> I found out that it is not the scroll bars causing this exceptions but the drag gestures on desktop @rydmike since I did this:
> 
> ```dart
> final scrollView = CustomScrollView(
>       scrollBehavior: (const DragScrollBehavior()).copyWith(scrollbars: false),
> ```

Looks correct. I forgot I added an official  Flutter example just for this behavior 
https://api.flutter.dev/flutter/widgets/RawScrollbar-class.html#cupertino.RawScrollbar.3

**Comment by ulusoyca** [comment]
> > I found out that it is not the scroll bars causing this exceptions but the drag gestures on desktop @rydmike since I did this:
> > ```dart
> > final scrollView = CustomScrollView(
> >       scrollBehavior: (const DragScrollBehavior()).copyWith(scrollbars: false),
> > ```
> 
> Looks correct. I forgot I added an official Flutter example just for this behavior https://api.flutter.dev/flutter/widgets/RawScrollbar-class.html#cupertino.RawScrollbar.3

Ok, however we still receive exceptions caused by drag to scroll gestures on listview in desktop app.

**Comment by TahaTesser** [comment]
Did you look at https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag?

**Comment by rydmike** [comment]
Perfect 💙👍

In this case dragscroll is causing extra scrollbars to appear, and you get multiple ones (two in the example issue case), this causes the default scroll controller to get confused about which scrollbar should be using it, it gets very unhappy when two scrollbars both inherit the same one.

Fix is like you did, disable the scrollbar(s) where not needed, only keep default scrollbars in one place. The scrollbar left is then no longer upset that another scrollbar is also using the same default controller. The issue then goes away.

Alternatively use separate scroll controllers for each scroll area and thus scrollbar. This is seldom desirable though (to have two scrollbars), but there are some rare use cases for it.

Both options work, I tried them when dealing with similar issue in the Themes Playground app.

**Comment by TahaTesser** [comment]
The error thrown in https://github.com/woltapp/wolt_modal_sheet/issues/46#issuecomment-1712503078 is very generic. 
If you could isolate the issue with a minimal sample It'll help debug the issue.

**Comment by TahaTesser** [comment]
Also worth testing this issue on a different Flutter branch to make sure it's not an error from Flutter itself e.g. master.

**Comment by ulusoyca** [comment]
I found out that this is due to shrinkWrap set to `true` in CustomScrollView

```dart
 CustomScrollView(
      scrollBehavior: ScrollConfiguration.of(context).copyWith(
        dragDevices: <PointerDeviceKind>{
          PointerDeviceKind.touch,
          PointerDeviceKind.mouse,
          PointerDeviceKind.trackpad,
          PointerDeviceKind.stylus,
        },
      ),
      shrinkWrap: true,
````


```dart
  /// Shrink wrapping the content of the scroll view is significantly more
  /// expensive than expanding to the maximum allowed size because the content
  /// can expand and contract during scrolling, which means the size of the
  /// scroll view needs to be recomputed whenever the scroll position changes.
  ```
ChatGPT says:
The error you're seeing, specifically the !debugNeedsLayout assertion failure, suggests that there's a widget in your tree that is being accessed or interacted with (in this case, during a hit test) before its layout phase is complete. This kind of error is often associated with how your widgets are being built, especially if you're doing dynamic or conditional widget construction.

**Comment by TahaTesser** [comment]
` shrinkWrap: true`

Should avoid using `shrinkWrap` anywhere in the package.  Please see https://github.com/flutter/flutter/issues/130360

**Comment by ulusoyca** [comment]
> flutter/flutter#130360

Ok, this is important, and quite new to me. The whole modal sheet layout calculations rely on `shrinkWrap`. I need to find a way of getting the implicit height of the main content during rendering to set the layout sheet which is sliver. Let's have a meeting about it when you have time.

**Comment by TahaTesser** [comment]
Sure thing

**Comment by yunusemrebakir** [comment]
I will create a separate issue to continue shrinkWrap and size calculation discussions.

**Comment by iyar-avital** [comment]
Same issue, can't solve.
What is the actual solution?
